### ISSUE TITLE
Not working in HassOS

### ISSUE THREAD

**Issue by denics** [jschlyter/hass-zway#1]
Hi, thanks for this. I have an issue trying to make it work with HassOS. I get:

```txt
Logger: homeassistant.config
Source: config.py:819
First occurred: 13:12:04 (1 occurrences)
Last logged: 13:12:04
Platform error: light - Integration 'zway' not found. 
```

I simply cloned your folder into my **custom_components** folder and enable it with:
```yaml
light:
  - platform: sensehat
  - platform: zway
    url: !secret zway_url
    username: !secret zway_user
    password: !secret zway_pass
    include: Lights
```

Am I missing something?
